version: '3'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:80"
    depends_on:
      - redis