# Generated by Django 2.1.5 on 2019-01-31 13:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='channel_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WebSocket Channel ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Device ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='Gilsa Device', max_length=50, verbose_name='Device Name'),
        ),
    ]
