# Generated by Django 2.1.5 on 2019-01-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevice', '0003_device_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified ?'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_connected',
            field=models.BooleanField(default=False, verbose_name='Is Connected ?'),
        ),
    ]
