# Generated by Django 2.1.5 on 2019-04-01 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevice', '0008_devicetype_latest_firmware'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gilsa Device', max_length=50, verbose_name='Device Category Name')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='iotdevice.DeviceCategory'),
        ),
    ]
