# Generated by Django 2.1.5 on 2019-04-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevice', '0009_auto_20190401_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.TextField(blank=True, null=True, verbose_name='Status in Json Format'),
        ),
    ]
