# Generated by Django 2.1.5 on 2019-05-15 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevice', '0010_device_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='category',
        ),
        migrations.AddField(
            model_name='devicetype',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='iotdevice.DeviceCategory'),
        ),
    ]
