# Generated by Django 2.1.5 on 2019-05-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevice', '0012_zone_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'پذیرایی'), (1, 'اتاق خواب'), (2, 'آشپزخانه'), (3, 'حمام')], default=0, verbose_name='Zone Type'),
        ),
    ]
