# Generated by Django 2.1.5 on 2019-05-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevice', '0013_auto_20190523_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(blank=True, default='No Name Zone', max_length=50, verbose_name='Zone Name'),
        ),
    ]
