# Generated by Django 2.1.5 on 2019-05-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevice', '0014_auto_20190523_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Device Category Code'),
        ),
    ]
