# Generated by Django 2.1.5 on 2019-05-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevice', '0015_devicecategory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='type',
            field=models.IntegerField(blank=True, default=0, verbose_name='Zone Type'),
        ),
    ]
