# Generated by Django 2.1.5 on 2019-05-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevice', '0016_auto_20190525_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.TextField(blank=True, default='{"a":"b"}', verbose_name='Status in Json Format'),
        ),
    ]
