# Generated by Django 2.1.5 on 2019-06-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevice', '0017_auto_20190526_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Command Code'),
        ),
        migrations.AlterUniqueTogether(
            name='command',
            unique_together={('code', 'device_type')},
        ),
    ]
