# Generated by Django 2.1.5 on 2019-06-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevice', '0018_auto_20190608_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='icon',
            field=models.ImageField(default='DeviceCategoryIcons/icon.png', upload_to='DeviceCategoryIcons/%Y/%m/%d', verbose_name='Icon'),
        ),
    ]
