# Generated by Django 2.1.5 on 2019-03-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevice', '0005_home_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gilsa Device', max_length=50, verbose_name='Device Type Name')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Device Type Code')),
                ('icon', models.ImageField(default='DeviceTypeIcons/icon.png', upload_to='DeviceTypeIcons/%Y/%m/%d', verbose_name='Icon')),
            ],
        ),
    ]
