# Generated by Django 2.1.5 on 2019-03-28 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iotdevice', '0006_command_devicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Command Code'),
        ),
        migrations.AddField(
            model_name='command',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Command Content'),
        ),
        migrations.AddField(
            model_name='command',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='iotdevice.DeviceType'),
        ),
        migrations.AddField(
            model_name='command',
            name='name',
            field=models.CharField(default='Gilsa Device', max_length=50, verbose_name='Command Name'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='iotdevice.DeviceType'),
        ),
        migrations.AddField(
            model_name='device',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='iotdevice.Home'),
        ),
        migrations.AddField(
            model_name='device',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='iotdevice.Zone'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='min_firmware_version',
            field=models.CharField(default='1.0.0', max_length=50, verbose_name='Device Type Minimum Firmware Version'),
        ),
        migrations.AddField(
            model_name='home',
            name='name',
            field=models.CharField(default='No Name Home', max_length=50, verbose_name='Home Name'),
        ),
        migrations.AddField(
            model_name='home',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_homes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zone',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='iotdevice.Home'),
        ),
        migrations.AddField(
            model_name='zone',
            name='name',
            field=models.CharField(default='No Name Zone', max_length=50, verbose_name='Zone Name'),
        ),
    ]
