# Generated by Django 2.1.5 on 2019-03-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KavenegarConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Name', max_length=200, verbose_name='Kavenegar Config Name')),
                ('api', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kavenegar API Key')),
                ('sender', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sender Number')),
                ('totalSMSCount', models.IntegerField(default=0, verbose_name='Total SMS count')),
                ('totalFailureCount', models.IntegerField(default=0, verbose_name='Total Failure count')),
                ('totalCost', models.FloatField(default=0, verbose_name='Total Cost in Tomans')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
