# Generated by Django 2.1.5 on 2019-05-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndriodUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Name', max_length=200, verbose_name='Config Name')),
                ('latest_version', models.FileField(default='', upload_to='Android/%Y/%m/%d', verbose_name='latest version')),
                ('min_version', models.CharField(default='0.0.0', max_length=50, verbose_name='Minimum acceptable Version')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IOSUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Name', max_length=200, verbose_name='Config Name')),
                ('latest_version', models.FileField(default='', upload_to='IOS/%Y/%m/%d', verbose_name='latest version')),
                ('min_version', models.CharField(default='0.0.0', max_length=50, verbose_name='Minimum acceptable Version')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
