# Generated by Django 2.1.5 on 2019-05-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20190514_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Splash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Splash', max_length=200, verbose_name='Config Name')),
                ('latest_version', models.FileField(default='', upload_to='Splash/%Y/%m/%d', verbose_name='latest version')),
                ('os', models.CharField(default='Android', max_length=200, verbose_name='OS Type')),
                ('min_version', models.CharField(default='0.0.0', max_length=50, verbose_name='Minimum acceptable Version')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AndriodUpdate',
        ),
        migrations.DeleteModel(
            name='IOSUpdate',
        ),
    ]
