# Generated by Django 2.1.5 on 2019-05-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_auto_20190514_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='splash',
            old_name='title',
            new_name='description',
        ),
        migrations.AddField(
            model_name='splash',
            name='download_url',
            field=models.URLField(default='', max_length=500, verbose_name='download link'),
        ),
        migrations.AlterField(
            model_name='splash',
            name='latest_version',
            field=models.URLField(default='', max_length=500, verbose_name='version link'),
        ),
    ]
