# Generated by Django 2.1.5 on 2019-03-27 20:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iotauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6d737670-1363-4c2e-b478-fc00f60e00e8'), unique=True, verbose_name='user unique id'),
        ),
    ]
