# Generated by Django 2.1.5 on 2019-03-27 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iotauth', '0002_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('09f77aef-d466-4f64-9304-fce0bec4f88b'), unique=True, verbose_name='user unique id'),
        ),
    ]
