# Generated by Django 2.1.5 on 2019-03-27 20:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iotauth', '0003_auto_20190328_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='user unique id'),
        ),
    ]
